# Generated by Django 5.0.6 on 2026-10-03 22:49

from django.db import migrations, models


def normalize_default_title(apps, schema_editor):
    Conversation = apps.get_model("chat", "Conversation")
    Conversation.objects.filter(title="New Chat").update(title="New chat")


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New chat', max_length=255),
        ),
        migrations.RunPython(normalize_default_title, migrations.RunPython.noop),
    ]
