# Generated by Django 5.0.6 on 2026-10-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_default_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
